# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageViewer(object):
    def setupUi(self, ImageViewer):
        ImageViewer.setObjectName("ImageViewer")
        ImageViewer.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ImageViewer)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.item_list = QtWidgets.QListWidget(self.centralwidget)
        self.item_list.setObjectName("item_list")
        self.verticalLayout.addWidget(self.item_list)
        self.search = QtWidgets.QLineEdit(self.centralwidget)
        self.search.setObjectName("search")
        self.verticalLayout.addWidget(self.search)
        self.next_image = QtWidgets.QPushButton(self.centralwidget)
        self.next_image.setObjectName("next_image")
        self.verticalLayout.addWidget(self.next_image)
        self.prev_image = QtWidgets.QPushButton(self.centralwidget)
        self.prev_image.setObjectName("prev_image")
        self.verticalLayout.addWidget(self.prev_image)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.image_label = QtWidgets.QLabel(self.centralwidget)
        self.image_label.setScaledContents(True)
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setObjectName("image_label")
        self.verticalLayout_2.addWidget(self.image_label)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.current_label = QtWidgets.QLabel(self.centralwidget)
        self.current_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.current_label.setObjectName("current_label")
        self.verticalLayout_2.addWidget(self.current_label)
        self.verticalLayout_2.setStretch(0, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(1, 1)
        ImageViewer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ImageViewer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        ImageViewer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ImageViewer)
        self.statusbar.setObjectName("statusbar")
        ImageViewer.setStatusBar(self.statusbar)
        self.actionOpen_Folder = QtWidgets.QAction(ImageViewer)
        self.actionOpen_Folder.setObjectName("actionOpen_Folder")
        self.actionOpen_Labels_Folder = QtWidgets.QAction(ImageViewer)
        self.actionOpen_Labels_Folder.setObjectName("actionOpen_Labels_Folder")
        self.actionForce_Update = QtWidgets.QAction(ImageViewer)
        self.actionForce_Update.setObjectName("actionForce_Update")
        self.menuFile.addAction(self.actionOpen_Folder)
        self.menuFile.addAction(self.actionOpen_Labels_Folder)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionForce_Update)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(ImageViewer)
        QtCore.QMetaObject.connectSlotsByName(ImageViewer)

    def retranslateUi(self, ImageViewer):
        _translate = QtCore.QCoreApplication.translate
        ImageViewer.setWindowTitle(_translate("ImageViewer", "MainWindow"))
        self.search.setPlaceholderText(_translate("ImageViewer", "Search..."))
        self.next_image.setText(_translate("ImageViewer", "Next"))
        self.prev_image.setText(_translate("ImageViewer", "Prev"))
        self.image_label.setText(_translate("ImageViewer", "TextLabel"))
        self.current_label.setText(_translate("ImageViewer", "None"))
        self.menuFile.setTitle(_translate("ImageViewer", "File"))
        self.actionOpen_Folder.setText(_translate("ImageViewer", "Open Data Folder"))
        self.actionOpen_Labels_Folder.setText(_translate("ImageViewer", "Open Labels Folder"))
        self.actionForce_Update.setText(_translate("ImageViewer", "Force Update"))
